In [9]:
import pandas as pd

In [10]:
file_path = '/home/mingkang/Desktop/bootes/paper2.csv'
df = pd.read_csv(file_path)

In [11]:
df.columns = ['name','ra','dec','snr','s850','s250','s350','s500','class','redshift','lir','sfr']

In [12]:
df

,name,ra,dec,snr,s850,s250,s350,s500,class,redshift,lir,sfr
0,Bootes1.01,218.569 19,35.549 17,7.8,9.9 (1.4),132.6 (6.3),96.0 (6.5),65.9 (6.9),cat,1.43+0.58−0.8,12.94+0.41−0.35,3.11+0.41−0.35
1,Bootes1.02,218.520 02,35.561 37,5.1,7.4 (1.5),23.8 (6.3),32.7 (6.5),32.2 (7.1),cat,2.72+0.77−0.44,12.83+0.28−0.15,3.0+0.28−0.15
2,Bootes1.03,218.559 63,35.561 39,4.6,5.3 (1.2),9.7 (6.3),18.7 (6.6),15.7 (7.2),map,3.41+0.88−0.76,12.67+0.22−0.19,2.85+0.22−0.19
3,Bootes1.04,218.651 15,35.576 92,4.5,7.5 (1.7),36.2 (6.3),33.2 (6.5),21.7 (6.9),cat,2.22+0.59−0.58,12.74+0.29−0.17,2.91+0.29−0.17
4,Bootes1.05,218.540 48,35.605 83,4.5,9.0 (2.1),17.9 (6.3),18.4 (6.6),27.9 (7.2),map,3.54+0.9−0.58,12.91+0.2−0.18,3.09+0.2−0.18
5,Bootes1.06,218.607 44,35.569 16,4.4,5.4 (1.3),10.1 (6.3),11.9 (6.6),9.0 (7.2),map,4.09+2.31−1.21,12.68+0.23−0.22,2.85+0.23−0.22
6,Bootes1.07,218.593 77,35.555 83,4.3,4.6 (1.1),−9.4 (6.3),16.7 (6.6),4.1 (7.2),map,8.09+4.66−3.34,12.82+0.3−0.29,2.99+0.3−0.29
7,Bootes1.08,218.573 29,35.579 17,4.1,4.6 (1.1),25.8 (6.3),25.1 (6.6),26.9 (7.3),cat,2.15+0.78−0.71,12.58+0.33−0.19,2.75+0.33−0.19
8,Bootes1.09,218.615 64,35.576 94,4.1,5.4 (1.4),−3.1 (6.3),4.1 (6.6),3.3 (7.2),map,10.18+3.29−3.78,12.97+0.26−0.28,3.15+0.26−0.28
9,Bootes1.10,218.588 30,35.492 50,4.0,7.1 (1.8),3.0 (6.3),1.8 (6.6),−2.6 (7.2),map,11.14+2.89−3.65,13.12+0.25−0.3,3.29+0.25−0.3
10,Bootes1.11,218.653 87,35.556 92,4.0,5.7 (1.5),2.8 (6.3),2.1 (6.6),−0.6 (7.2),map,10.54+3.13−4.01,13.01+0.26−0.32,3.18+0.26−0.32
11,Bootes1.12,218.563 74,35.491 39,4.0,6.2 (1.6),23.1 (6.3),32.6 (6.6),24.5 (7.2),cat,2.54+0.86−0.51,12.74+0.3−0.16,2.91+0.3−0.16

In [13]:
# for the s850 column, take out the bracketed number and put in a new column
df['err_850'] = df['s850'].str.extract(r'\((\d+\.\d+)\)',expand=False)
df['err_250'] = df['s250'].str.extract(r'\((\d+\.\d+)\)',expand=False)
df['err_350'] = df['s350'].str.extract(r'\((\d+\.\d+)\)',expand=False)
df['err_500'] = df['s500'].str.extract(r'\((\d+\.\d+)\)',expand=False)
df['s850'] = df['s850'].str.extract(r'(\d+\.\d+)',expand=False)
df['s250'] = df['s250'].str.extract(r'(\d+\.\d+)',expand=False)
df['s350'] = df['s350'].str.extract(r'(\d+\.\d+)',expand=False)
df['s500'] = df['s500'].str.extract(r'(\d+\.\d+)',expand=False)

In [14]:
df

,name,ra,dec,snr,s850,s250,s350,s500,class,redshift,lir,sfr,err_850,err_250,err_350,err_500
0,Bootes1.01,218.569 19,35.549 17,7.8,9.9,132.6,96.0,65.9,cat,1.43+0.58−0.8,12.94+0.41−0.35,3.11+0.41−0.35,1.4,6.3,6.5,6.9
1,Bootes1.02,218.520 02,35.561 37,5.1,7.4,23.8,32.7,32.2,cat,2.72+0.77−0.44,12.83+0.28−0.15,3.0+0.28−0.15,1.5,6.3,6.5,7.1
2,Bootes1.03,218.559 63,35.561 39,4.6,5.3,9.7,18.7,15.7,map,3.41+0.88−0.76,12.67+0.22−0.19,2.85+0.22−0.19,1.2,6.3,6.6,7.2
3,Bootes1.04,218.651 15,35.576 92,4.5,7.5,36.2,33.2,21.7,cat,2.22+0.59−0.58,12.74+0.29−0.17,2.91+0.29−0.17,1.7,6.3,6.5,6.9
4,Bootes1.05,218.540 48,35.605 83,4.5,9.0,17.9,18.4,27.9,map,3.54+0.9−0.58,12.91+0.2−0.18,3.09+0.2−0.18,2.1,6.3,6.6,7.2
5,Bootes1.06,218.607 44,35.569 16,4.4,5.4,10.1,11.9,9.0,map,4.09+2.31−1.21,12.68+0.23−0.22,2.85+0.23−0.22,1.3,6.3,6.6,7.2
6,Bootes1.07,218.593 77,35.555 83,4.3,4.6,9.4,16.7,4.1,map,8.09+4.66−3.34,12.82+0.3−0.29,2.99+0.3−0.29,1.1,6.3,6.6,7.2
7,Bootes1.08,218.573 29,35.579 17,4.1,4.6,25.8,25.1,26.9,cat,2.15+0.78−0.71,12.58+0.33−0.19,2.75+0.33−0.19,1.1,6.3,6.6,7.3
8,Bootes1.09,218.615 64,35.576 94,4.1,5.4,3.1,4.1,3.3,map,10.18+3.29−3.78,12.97+0.26−0.28,3.15+0.26−0.28,1.4,6.3,6.6,7.2
9,Bootes1.10,218.588 30,35.492 50,4.0,7.1,3.0,1.8,2.6,map,11.14+2.89−3.65,13.12+0.25−0.3,3.29+0.25−0.3,1.8,6.3,6.6,7.2
10,Bootes1.11,218.653 87,35.556 92,4.0,5.7,2.8,2.1,0.6,map,10.54+3.13−4.01,13.01+0.26−0.32,3.18+0.26−0.32,1.5,6.3,6.6,7.2
11,Bootes1.12,218.563 74,35.491 39,4.0,6.2,23.1,32.6,24.5,cat,2.54+0.86−0.51,12.74+0.3−0.16,2.91+0.3−0.16,1.6,6.3,6.6,7.2

In [9]:
# multiply the fluxes by 1e-3 to get them in Jy
df['s850'] = df['s850'].astype(float) * 1e-3
df['s250'] = df['s250'].astype(float) * 1e-3
df['s350'] = df['s350'].astype(float) * 1e-3
df['s500'] = df['s500'].astype(float) * 1e-3

# multiply the errors by 1e-3 to get them in Jy
df['err_850'] = df['err_850'].astype(float) * 1e-3
df['err_250'] = df['err_250'].astype(float) * 1e-3
df['err_350'] = df['err_350'].astype(float) * 1e-3
df['err_500'] = df['err_500'].astype(float) * 1e-3

In [12]:
df['z_spec'] = -99

In [9]:
df2 = df[['name','z_spec','s850','err_850','s250','err_250','s350','err_350','s500','err_500']]

In [11]:
df2.to_csv('obervations.dat',sep='\t',index=False)